"""
generate_report.py
------------------
Renders report/phase1_report.md from pre-computed stats JSON files and
generated plot images.

This script reads:
  - hindi/data/stats.json
  - nepali/data/stats.json
  - report/figures/*.png  (generated by plots.py)

And writes:
  - report/phase1_report.md

Usage
-----
  python generate_report.py \\
      --hindi-stats  hindi/data/stats.json \\
      --nepali-stats nepali/data/stats.json \\
      --figures-dir  report/figures/ \\
      --output       report/phase1_report.md \\
      --repo-root    .
"""

import argparse
import json
import sys
from pathlib import Path


def _load(path: str) -> dict:
    """Load a stats JSON file, returning {} on failure."""
    p = Path(path)
    if not p.exists():
        print(f"[generate_report] WARNING: {p} not found. Report will have gaps.", file=sys.stderr)
        return {}
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def _fmt_int(v) -> str:
    """Format an integer with commas."""
    try:
        return f"{int(v):,}"
    except (TypeError, ValueError):
        return str(v) if v is not None else "N/A"


def _fmt_float(v, decimals=2) -> str:
    try:
        return f"{float(v):.{decimals}f}"
    except (TypeError, ValueError):
        return str(v) if v is not None else "N/A"


def render_filter_table(filter_table: list) -> str:
    """Render the stage-by-stage filtering table as markdown."""
    header = (
        "| Stage | Docs In | Docs Dropped | Tokens In (est.) | Tokens Dropped (est.) |\n"
        "|---|---|---|---|---|\n"
    )
    rows = ""
    for r in filter_table:
        rows += (
            f"| {r.get('stage', '')} "
            f"| {_fmt_int(r.get('docs_in', 0))} "
            f"| {_fmt_int(r.get('docs_dropped', 0))} "
            f"| {_fmt_int(r.get('tokens_in_est', 0))} "
            f"| {_fmt_int(r.get('tokens_dropped_est', 0))} |\n"
        )
    return header + rows


def render_source_table(source_table: list) -> str:
    """Render the per-source statistics table as markdown."""
    header = (
        "| Source | Raw Docs | Raw Tokens (est.) | Final Docs | Final Tokens (est.) | Manual? |\n"
        "|---|---|---|---|---|---|\n"
    )
    rows = ""
    for r in source_table:
        rows += (
            f"| {r.get('source_name', '')} "
            f"| {_fmt_int(r.get('raw_docs', 0))} "
            f"| {_fmt_int(r.get('raw_tokens_est', 0))} "
            f"| {_fmt_int(r.get('final_docs', 0))} "
            f"| {_fmt_int(r.get('final_tokens_est', 0))} "
            f"| {r.get('manual', 'No')} |\n"
        )
    return header + rows


def render_sweep_table(sweep: list) -> str:
    """Render the vocabulary sweep comparison table."""
    header = (
        "| Vocab Size | Fertility | Avg Chars/Token | UNK Rate (%) | Compression Ratio |\n"
        "|---|---|---|---|---|\n"
    )
    rows = ""
    for r in sweep:
        rows += (
            f"| {_fmt_int(r.get('vocab_size', ''))} "
            f"| {_fmt_float(r.get('fertility', ''))} "
            f"| {_fmt_float(r.get('avg_chars_per_token', r.get('avg_chars', '')))} "
            f"| {_fmt_float(float(r.get('unk_rate', 0)) * 100, 4)} "
            f"| {_fmt_float(r.get('compression_ratio', ''))} |\n"
        )
    return header + rows


def render_examples(examples: list) -> str:
    """Render tokenization examples as a markdown list."""
    if not examples:
        return "_No examples available._\n"
    lines = []
    for i, ex in enumerate(examples[:5], 1):
        orig   = ex.get("original", "")
        tokens = ex.get("tokens", [])
        n      = ex.get("n_tokens", len(tokens))
        lines.append(f"{i}. **Input:** {orig}")
        lines.append(f"   **Tokens ({n}):** `{'` `'.join(str(t) for t in tokens)}`")
        lines.append("")
    return "\n".join(lines)


def render_report(
    sh: dict,
    sn: dict,
    figures_dir: Path,
    repo_root: Path,
) -> str:
    """
    Render the full Phase 1 report as a markdown string.

    Parameters
    ----------
    sh : dict
        Hindi stats.
    sn : dict
        Nepali stats.
    figures_dir : Path
    repo_root : Path

    Returns
    -------
    str
        Full markdown report.
    """
    def _split_stat(stats: dict, split: str, key: str) -> str:
        return _fmt_int(stats.get("splits", {}).get(split, {}).get(key, 0))

    def _tok(stats: dict, key: str) -> str:
        return str(stats.get("tokenizer", {}).get(key, "N/A"))

    def _bd(stats: dict, key: str) -> str:
        return str(stats.get("manual_breakdown", {}).get(key, "N/A"))

    fig_path = lambda name: str(figures_dir / f"{name}.png")

    h_compliant = sh.get("manual_breakdown", {}).get("compliant", False)
    n_compliant = sn.get("manual_breakdown", {}).get("compliant", False)

    report = f"""# Phase 1 Report: Data Collection & Tokenizer Construction

**Languages:** Hindi (Model H, higher-resource) ?? Nepali (Model L, lower-resource)
**Date:** <!-- fill in -->
**Author:** <!-- fill in -->

---

## 1. Language Selection Justification

<!-- TODO: Fill in your justification for choosing Hindi (higher-resource) and
Nepali (lower-resource). Consider: data availability, script relationship,
linguistic distance, research interest. -->

---

## 2. Pipeline Overview

The data pipeline follows 18 stages as described in the Phase 1 specification.
The test holdout is frozen **before** any cleaning or deduplication occurs,
preventing any information about the test distribution from influencing
cleaning decisions, deduplication groupings, or tokenizer vocabulary.

### 2.1 Stage-by-Stage Filtering ??? Hindi

{render_filter_table(sh.get('filter_table', []))}

### 2.2 Stage-by-Stage Filtering ??? Nepali

{render_filter_table(sn.get('filter_table', []))}

---

## 3. Data Sources

### 3.1 Source Overview ??? Hindi

{render_source_table(sh.get('source_table', []))}

### 3.2 Source Overview ??? Nepali

{render_source_table(sn.get('source_table', []))}

#### Nepali Data Shortfall

<!-- TODO: If Nepali did not reach 500M tokens, fill in the exact shortfall
and reasons here. Use the information from nepali/data/shortfall_log.json. -->

---

## 4. Corpus Statistics

| Metric | Hindi | Nepali |
|---|---|---|
| Train Documents | {_split_stat(sh, 'train', 'n_docs')} | {_split_stat(sn, 'train', 'n_docs')} |
| Train Tokens (whitespace) | {_split_stat(sh, 'train', 'total_tokens')} | {_split_stat(sn, 'train', 'total_tokens')} |
| Val Documents | {_split_stat(sh, 'val', 'n_docs')} | {_split_stat(sn, 'val', 'n_docs')} |
| Val Tokens | {_split_stat(sh, 'val', 'total_tokens')} | {_split_stat(sn, 'val', 'total_tokens')} |
| Test Documents | {_split_stat(sh, 'test', 'n_docs')} | {_split_stat(sn, 'test', 'n_docs')} |
| Test Tokens | {_split_stat(sh, 'test', 'total_tokens')} | {_split_stat(sn, 'test', 'total_tokens')} |

### 4.1 Manual vs. Downloaded Token Breakdown

| Metric | Hindi | Nepali |
|---|---|---|
| Manual tokens (%) | {_bd(sh, 'manual_pct')}% | {_bd(sn, 'manual_pct')}% |
| Downloaded tokens (%) | {_bd(sh, 'downloaded_pct') if 'downloaded_pct' in sh.get('manual_breakdown', {}) else 'N/A'}% | {_bd(sn, 'downloaded_pct') if 'downloaded_pct' in sn.get('manual_breakdown', {}) else 'N/A'}% |
| ??? 20% requirement | {'??? PASS' if h_compliant else '??? FAIL'} | {'??? PASS' if n_compliant else '??? FAIL'} |

![Manual vs. Downloaded Fraction]({fig_path('manual_fraction')})

### 4.2 Source Contributions

![Source Contributions]({fig_path('source_contribution')})

### 4.3 Pipeline Funnel

![Pipeline Funnel]({fig_path('pipeline_funnel')})

---

## 5. Filtering Threshold Rationale

<!-- TODO: For each threshold in filtering_thresholds.yaml, paste the
distribution statistics from recon.py output and explain how you chose
the threshold value. This is required by Hard Constraint 7. -->

---

## 6. Tokenizer Construction

### 6.1 Method

- **Algorithm:** SentencePiece Unigram (configurable to BPE via tokenizer_config.yaml)
- **Training data:** train.jsonl only (val and test text excluded to prevent vocabulary leakage)
- **Languages:** trained independently; no shared vocabulary

### 6.2 Vocabulary Sweep ??? Hindi

{render_sweep_table(sh.get('vocab_sweep', []))}

**Selected vocab size (Hindi):** <!-- fill in from tokenizer_config.yaml: final_vocab_size -->

**Rationale:** <!-- fill in -->

### 6.3 Vocabulary Sweep ??? Nepali

{render_sweep_table(sn.get('vocab_sweep', []))}

**Selected vocab size (Nepali):** <!-- fill in from tokenizer_config.yaml: final_vocab_size -->

**Rationale:** <!-- fill in -->

![Vocabulary Sweep]({fig_path('vocab_sweep')})

### 6.4 Tokenizer Statistics

| Metric | Hindi | Nepali |
|---|---|---|
| Vocab size | {_tok(sh, 'vocab_size')} | {_tok(sn, 'vocab_size')} |
| Avg chars / token | {_tok(sh, 'avg_chars_per_token')} | {_tok(sn, 'avg_chars_per_token')} |
| Fertility (tokens/word) | {_tok(sh, 'fertility')} | {_tok(sn, 'fertility')} |
| UNK rate | {_tok(sh, 'unk_rate_pct')}% | {_tok(sn, 'unk_rate_pct')}% |
| Compression ratio | {_tok(sh, 'compression_ratio')} | {_tok(sn, 'compression_ratio')} |

### 6.5 Top-20 Tokens

**Hindi:**
{', '.join(f'`{t["token"]}`' for t in sh.get('tokenizer', {}).get('top_tokens', [])[:20])}

**Nepali:**
{', '.join(f'`{t["token"]}`' for t in sn.get('tokenizer', {}).get('top_tokens', [])[:20])}

### 6.6 Tokenization Examples

**Hindi:**

{render_examples(sh.get('tokenizer', {}).get('examples', []))}

**Nepali:**

{render_examples(sn.get('tokenizer', {}).get('examples', []))}

---

## 7. Known Limitations and Future Work

- **Nepali OCR:** If `nep` Tesseract traineddata was unavailable, `hin` traineddata was used as a fallback. OCR error rates for Nepali text using this fallback are estimated at <!-- fill in %  -->.
- **Language ID confusions:** fastText lid.176.bin may mis-classify short Nepali documents as Hindi. The heuristic Devanagari script fallback accepts documents with ??? 40% Devanagari characters regardless of classifier confidence.
- **Safety filter coverage:** The semantic/safety pattern lists are minimal seed lists. Manual review of rejected documents is required and documented in `nepali/data/dedup/rejected_nepali.jsonl` and `hindi/data/dedup/rejected_hindi.jsonl`.

---

*This report was auto-generated by `common/stats/generate_report.py`.
All statistics are derived from manifest.csv and the pre-computed stats JSON files.
Prose sections marked <!-- TODO --> require manual completion before submission.*
"""
    return report


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Render phase1_report.md from pre-computed stats.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--hindi-stats",  required=True)
    parser.add_argument("--nepali-stats", required=True)
    parser.add_argument("--figures-dir",  default="report/figures/")
    parser.add_argument("--output",       default="report/phase1_report.md")
    parser.add_argument("--repo-root",    default=".")
    return parser.parse_args()


def main() -> None:
    """Load stats and render the Phase 1 markdown report."""
    args = parse_args()
    repo_root   = Path(args.repo_root).resolve()
    figures_dir = Path(args.figures_dir)

    sh = _load(args.hindi_stats)
    sn = _load(args.nepali_stats)

    report_md = render_report(sh, sn, figures_dir, repo_root)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(report_md)

    print(f"[generate_report] Phase 1 report written -> {out_path}")
    print("  Fill in all <!-- TODO --> sections before submission.")


if __name__ == "__main__":
    main()
